<?php

$text['title-clients']['en-us'] = "Clients";
$text['title-clients']['en-gb'] = "Clients";
$text['title-clients']['ar-eg'] = "";
$text['title-clients']['de-at'] = ""; //copied from de-de
$text['title-clients']['de-ch'] = ""; //copied from de-de
$text['title-clients']['de-de'] = "";
$text['title-clients']['es-cl'] = "";
$text['title-clients']['es-mx'] = ""; //copied from es-cl
$text['title-clients']['fr-ca'] = ""; //copied from fr-fr
$text['title-clients']['fr-fr'] = "";
$text['title-clients']['he-il'] = "";
$text['title-clients']['it-it'] = "";
$text['title-clients']['nl-nl'] = "";
$text['title-clients']['pl-pl'] = "";
$text['title-clients']['pt-br'] = "";
$text['title-clients']['pt-pt'] = "";
$text['title-clients']['ro-ro'] = "";
$text['title-clients']['ru-ru'] = "";
$text['title-clients']['sv-se'] = "";
$text['title-clients']['uk-ua'] = "";

$text['title-client-edit']['en-us'] = "Client Edit";
$text['title-client-edit']['en-gb'] = "Client Edit";
$text['title-client-edit']['ar-eg'] = "";
$text['title-client-edit']['de-at'] = ""; //copied from de-de
$text['title-client-edit']['de-ch'] = ""; //copied from de-de
$text['title-client-edit']['de-de'] = "";
$text['title-client-edit']['es-cl'] = "";
$text['title-client-edit']['es-mx'] = ""; //copied from es-cl
$text['title-client-edit']['fr-ca'] = ""; //copied from fr-fr
$text['title-client-edit']['fr-fr'] = "";
$text['title-client-edit']['he-il'] = "";
$text['title-client-edit']['it-it'] = "";
$text['title-client-edit']['nl-nl'] = "";
$text['title-client-edit']['pl-pl'] = "";
$text['title-client-edit']['pt-br'] = "";
$text['title-client-edit']['pt-pt'] = "";
$text['title-client-edit']['ro-ro'] = "";
$text['title-client-edit']['ru-ru'] = "";
$text['title-client-edit']['sv-se'] = "";
$text['title-client-edit']['uk-ua'] = "";

$text['title-client-add']['en-us'] = "Client Add";
$text['title-client-add']['en-gb'] = "Client Add";
$text['title-client-add']['ar-eg'] = "";
$text['title-client-add']['de-at'] = ""; //copied from de-de
$text['title-client-add']['de-ch'] = ""; //copied from de-de
$text['title-client-add']['de-de'] = "";
$text['title-client-add']['es-cl'] = "";
$text['title-client-add']['es-mx'] = ""; //copied from es-cl
$text['title-client-add']['fr-ca'] = ""; //copied from fr-fr
$text['title-client-add']['fr-fr'] = "";
$text['title-client-add']['he-il'] = "";
$text['title-client-add']['it-it'] = "";
$text['title-client-add']['nl-nl'] = "";
$text['title-client-add']['pl-pl'] = "";
$text['title-client-add']['pt-br'] = "";
$text['title-client-add']['pt-pt'] = "";
$text['title-client-add']['ro-ro'] = "";
$text['title-client-add']['ru-ru'] = "";
$text['title-client-add']['sv-se'] = "";
$text['title-client-add']['uk-ua'] = "";

$text['title-clients_import']['en-us'] = "Client Import";
$text['title-clients_import']['en-gb'] = "Client Import";
$text['title-clients_import']['ar-eg'] = "";
$text['title-clients_import']['de-at'] = "Importieren"; //copied from de-de
$text['title-clients_import']['de-ch'] = "Importieren"; //copied from de-de
$text['title-clients_import']['de-de'] = "Importieren";
$text['title-clients_import']['el-gr'] = "Εισαγωγή";
$text['title-clients_import']['es-cl'] = "Importar";
$text['title-clients_import']['es-mx'] = "Importar"; //copied from es-cl
$text['title-clients_import']['fr-ca'] = "Importer"; //copied from fr-fr
$text['title-clients_import']['fr-fr'] = "Importer";
$text['title-clients_import']['he-il'] = "";
$text['title-clients_import']['it-it'] = "";
$text['title-clients_import']['nl-nl'] = "";
$text['title-clients_import']['pl-pl'] = "Importuj";
$text['title-clients_import']['pt-br'] = "Importar";
$text['title-clients_import']['pt-pt'] = "Importat";
$text['title-clients_import']['ro-ro'] = "";
$text['title-clients_import']['ru-ru'] = "Импорт";
$text['title-clients_import']['sv-se'] = "Importera";
$text['title-clients_import']['uk-ua'] = "";
$text['title-clients_import']['tr-tr'] = "İçe Aktar";

$text['label-client_uuid']['en-us'] = "Unique Client Identifier";
$text['label-access_code']['en-us'] = "Client Access Code";
$text['label-active']['en-us'] = "Client Active Status";
$text['label-invoice']['en-us'] = "Invoice";
$text['label-contract_number']['en-us'] = "Contract Number";
$text['label-client_id']['en-us'] = "Client ID";
$text['label-otp_sp_in']['en-us'] = "Over-the-Phone Special Instructions";
$text['label-otp_instructions']['en-us'] = "Over-the-Phone Instructions";
$text['label-sp_type']['en-us'] = "Special Instruction Type";
$text['label-invoice_detail']['en-us'] = "Invoice Information";
$text['label-client_name']['en-us'] = "Client Name";
$text['label-agency']['en-us'] = "Agency";
$text['label-division']['en-us'] = "Division";
$text['label-county']['en-us'] = "County";
$text['label-account_number']['en-us'] = "Account Number ";
$text['label-div_contact']['en-us'] = "Division Contact";
$text['label-div_address']['en-us'] = "Division Address";
$text['label-div_street']['en-us'] = "Division Street";
$text['label-div_building']['en-us'] = "Division Building";
$text['label-div_suite']['en-us'] = "Division Suite";
$text['label-div_city']['en-us'] = "Division City";
$text['label-div_state']['en-us'] = "Division State";
$text['label-div_zip']['en-us'] = "Division Zip";
$text['label-div_phone']['en-us'] = "Division Phone";
$text['label-div_fax']['en-us'] = "Division Fax";
$text['label-div_email']['en-us'] = "Division Email";
$text['label-bil_contact']['en-us'] = "Billing Contact";
$text['label-bil_address']['en-us'] = "Billing Address";
$text['label-bill_to_1']['en-us'] = "Billing To 1";
$text['label-bill_to_2']['en-us'] = "Billing To 2";
$text['label-bill_street']['en-us'] = "Billing Street";
$text['label-bill_bulding_name']['en-us'] = "Billing Building Name";
$text['label-bill_suite']['en-us'] = "Billing Suite";
$text['label-bill_city']['en-us'] = "Billing City";
$text['label-bill_state']['en-us'] = "Billing State";
$text['label-bill_zip']['en-us'] = "Billing Zip";
$text['label-bil_phone']['en-us'] = "Billing Phone";
$text['label-bil_fax']['en-us'] = "Billing Fax";
$text['label-bil_email']['en-us'] = "Billing Email";
$text['label-otpls1']['en-us'] = "Over-the-Phone Language Set 1";
$text['label-otpls2']['en-us'] = "Over-the-Phone Language Set 2";
$text['label-otpls3']['en-us'] = "Over-the-Phone Language Set 3";
$text['label-otpls4']['en-us'] = "Over-the-Phone Language Set 4";
$text['label-otpls1a']['en-us'] = "Over-the-Phone Language Set 1 After Hours";
$text['label-otpls2a']['en-us'] = "Over-the-Phone Language Set 2 After Hours";
$text['label-otpls3a']['en-us'] = "Over-the-Phone Language Set 3 After Hours";
$text['label-otpls4a']['en-us'] = "Over-the-Phone Language Set 4 After Hours";
$text['label-osls1']['en-us'] = "Onsite Language Set 1";
$text['label-osls2']['en-us'] = "Onsite Language Set 2";
$text['label-osls3']['en-us'] = "Onsite Language Set 3";
$text['label-osls4']['en-us'] = "Onsite Language Set 4";
$text['label-osahf']['en-us'] = "Onsite After Hours Fee";
$text['label-osrf']['en-us'] = "Onsite Rush Fee";
$text['label-osrt']['en-us'] = "Onsite Rush Time";
$text['label-oscf']['en-us'] = "Onsite Cancellation Fee";
$text['label-osct']['en-us'] = "Onsite Cancellation Time";
$text['label-onsite_instructions']['en-us'] = "Onsite Instructions";
$text['label-charge_callout']['en-us'] = "Charge for Callout";
$text['label-rate_callout']['en-us'] = "Rate for Callout";
$text['label-special_invoice']['en-us'] = "Special Invoice ";
$text['label-vrisl1']['en-us'] = "Video Remote Interpreting Language Set 1";
$text['label-vrisl2']['en-us'] = "Video Remote Interpreting Language Set 2";
$text['label-vrisl3']['en-us'] = "Video Remote Interpreting Language Set 3";
$text['label-vrisl4']['en-us'] = "Video Remote Interpreting Language Set 4";
$text['label-vricf']['en-us'] = "Video Remote Interpreting Cancellation Fee";
$text['label-vrict']['en-us'] = "Video Remote Interpreting Cancellation Time";
$text['label-vriahf']['en-us'] = "Video Remote Interpreting After Hours Fee";
$text['label-tls1']['en-us'] = "Translation Rate Language Set 1";
$text['label-tls2']['en-us'] = "Translation Rate Language Set 2";
$text['label-tls3']['en-us'] = "Translation Rate Language Set 3";
$text['label-tls4']['en-us'] = "Translation Rate Language Set 4";
$text['label-tff']['en-us'] = "Translation Formatting Fee";
$text['label-trf']['en-us'] = "Translation Rush Fee";

$text['header-clients']['en-us'] = "Clients";
$text['header-clients']['en-gb'] = "Clients";
$text['header-clients']['ar-eg'] = "";
$text['header-clients']['de-at'] = ""; //copied from de-de
$text['header-clients']['de-ch'] = ""; //copied from de-de
$text['header-clients']['de-de'] = "";
$text['header-clients']['es-cl'] = "";
$text['header-clients']['es-mx'] = ""; //copied from es-cl
$text['header-clients']['fr-ca'] = ""; //copied from fr-fr
$text['header-clients']['fr-fr'] = "";
$text['header-clients']['he-il'] = "";
$text['header-clients']['it-it'] = "";
$text['header-clients']['nl-nl'] = "";
$text['header-clients']['pl-pl'] = "";
$text['header-clients']['pt-br'] = "";
$text['header-clients']['pt-pt'] = "";
$text['header-clients']['ro-ro'] = "";
$text['header-clients']['ru-ru'] = "";
$text['header-clients']['sv-se'] = "";
$text['header-clients']['uk-ua'] = "";

$text['header-client-edit']['en-us'] = "Client Edit";
$text['header-client-edit']['en-gb'] = "Client Edit";
$text['header-client-edit']['ar-eg'] = "";
$text['header-client-edit']['de-at'] = ""; //copied from de-de
$text['header-client-edit']['de-ch'] = ""; //copied from de-de
$text['header-client-edit']['de-de'] = "";
$text['header-client-edit']['es-cl'] = "";
$text['header-client-edit']['es-mx'] = ""; //copied from es-cl
$text['header-client-edit']['fr-ca'] = ""; //copied from fr-fr
$text['header-client-edit']['fr-fr'] = "";
$text['header-client-edit']['he-il'] = "";
$text['header-client-edit']['it-it'] = "";
$text['header-client-edit']['nl-nl'] = "";
$text['header-client-edit']['pl-pl'] = "";
$text['header-client-edit']['pt-br'] = "";
$text['header-client-edit']['pt-pt'] = "";
$text['header-client-edit']['ro-ro'] = "";
$text['header-client-edit']['ru-ru'] = "";
$text['header-client-edit']['sv-se'] = "";
$text['header-client-edit']['uk-ua'] = "";

$text['header-client-add']['en-us'] = "Client Add";
$text['header-client-add']['en-gb'] = "Client Add";
$text['header-client-add']['ar-eg'] = "";
$text['header-client-add']['de-at'] = ""; //copied from de-de
$text['header-client-add']['de-ch'] = ""; //copied from de-de
$text['header-client-add']['de-de'] = "";
$text['header-client-add']['es-cl'] = "";
$text['header-client-add']['es-mx'] = ""; //copied from es-cl
$text['header-client-add']['fr-ca'] = ""; //copied from fr-fr
$text['header-client-add']['fr-fr'] = "";
$text['header-client-add']['he-il'] = "";
$text['header-client-add']['it-it'] = "";
$text['header-client-add']['nl-nl'] = "";
$text['header-client-add']['pl-pl'] = "";
$text['header-client-add']['pt-br'] = "";
$text['header-client-add']['pt-pt'] = "";
$text['header-client-add']['ro-ro'] = "";
$text['header-client-add']['ru-ru'] = "";
$text['header-client-add']['sv-se'] = "";
$text['header-client-add']['uk-ua'] = "";

$text['header-clients_import']['en-us'] = "Client Import";
$text['header-clients_import']['en-gb'] = "Client Import";
$text['header-clients_import']['ar-eg'] = "";
$text['header-clients_import']['de-at'] = "Importieren"; //copied from de-de
$text['header-clients_import']['de-ch'] = "Importieren"; //copied from de-de
$text['header-clients_import']['de-de'] = "Importieren";
$text['header-clients_import']['el-gr'] = "Εισαγωγή";
$text['header-clients_import']['es-cl'] = "Importar";
$text['header-clients_import']['es-mx'] = "Importar"; //copied from es-cl
$text['header-clients_import']['fr-ca'] = "Importer"; //copied from fr-fr
$text['header-clients_import']['fr-fr'] = "Importer";
$text['header-clients_import']['he-il'] = "";
$text['header-clients_import']['it-it'] = "";
$text['header-clients_import']['nl-nl'] = "";
$text['header-clients_import']['pl-pl'] = "Importuj";
$text['header-clients_import']['pt-br'] = "Importar";
$text['header-clients_import']['pt-pt'] = "Importat";
$text['header-clients_import']['ro-ro'] = "";
$text['header-clients_import']['ru-ru'] = "Импорт";
$text['header-clients_import']['sv-se'] = "Importera";
$text['header-clients_import']['uk-ua'] = "";
$text['header-clients_import']['tr-tr'] = "İçe Aktar";

$text['description-access_code']['en-us'] = "Enter the client access code.";
$text['description-active']['en-us'] = "Enter the client active status.";
$text['description-invoice']['en-us'] = "Enter the invoice.";
$text['description-contract_number']['en-us'] = "Enter the contract number.";
$text['description-client_id']['en-us'] = "Enter the client id.";
$text['description-otp_sp_in']['en-us'] = "Enter the over-the-phone special instructions.";
$text['description-otp_instructions']['en-us'] = "Enter the over-the-phone instructions.";
$text['description-sp_type']['en-us'] = "Enter the special instruction type.";
$text['description-invoice_detail']['en-us'] = "Enter the invoice information.";
$text['description-client_name']['en-us'] = "Enter the client name.";
$text['description-agency']['en-us'] = "Enter the agency.";
$text['description-division']['en-us'] = "Enter the division.";
$text['description-county']['en-us'] = "Enter the county.";
$text['description-account_number']['en-us'] = "Enter the account number.";
$text['description-div_contact']['en-us'] = "Enter the division contact.";
$text['description-div_address']['en-us'] = "Enter the division address.";
$text['description-div_street']['en-us'] = "Enter the division street.";
$text['description-div_building']['en-us'] = "Enter the division building.";
$text['description-div_suite']['en-us'] = "Enter the division suite.";
$text['description-div_city']['en-us'] = "Enter the division city.";
$text['description-div_state']['en-us'] = "Enter the division state.";
$text['description-div_zip']['en-us'] = "Enter the division zip.";
$text['description-div_phone']['en-us'] = "Enter the division phone.";
$text['description-div_fax']['en-us'] = "Enter the division fax.";
$text['description-div_email']['en-us'] = "Enter the division email.";
$text['description-bil_contact']['en-us'] = "Enter the billing contact.";
$text['description-bil_address']['en-us'] = "Enter the billing address.";
$text['description-bill_to_1']['en-us'] = "Enter the billing to 1.";
$text['description-bill_to_2']['en-us'] = "Enter the billing to 2.";
$text['description-bill_street']['en-us'] = "Enter the billing street.";
$text['description-bill_bulding_name']['en-us'] = "Enter the billing building name.";
$text['description-bill_suite']['en-us'] = "Enter the billing suite.";
$text['description-bill_city']['en-us'] = "Enter the billing city.";
$text['description-bill_state']['en-us'] = "Enter the billing state.";
$text['description-bill_zip']['en-us'] = "Enter the billing zip.";
$text['description-bil_phone']['en-us'] = "Enter the billing phone.";
$text['description-bil_fax']['en-us'] = "Enter the billing fax.";
$text['description-bil_email']['en-us'] = "Enter the billing email.";
$text['description-otpls1']['en-us'] = "Enter the over-the-phone language set 1.";
$text['description-otpls2']['en-us'] = "Enter the over-the-phone language set 2.";
$text['description-otpls3']['en-us'] = "Enter the over-the-phone language set 3.";
$text['description-otpls4']['en-us'] = "Enter the over-the-phone language set 4.";
$text['description-otpls1a']['en-us'] = "Enter the over-the-phone language set 1 after hours.";
$text['description-otpls2a']['en-us'] = "Enter the over-the-phone language set 2 after hours.";
$text['description-otpls3a']['en-us'] = "Enter the over-the-phone language set 3 after hours.";
$text['description-otpls4a']['en-us'] = "Enter the over-the-phone language set 4 after hours.";
$text['description-osls1']['en-us'] = "Enter the onsite language set 1.";
$text['description-osls2']['en-us'] = "Enter the onsite language set 2.";
$text['description-osls3']['en-us'] = "Enter the onsite language set 3.";
$text['description-osls4']['en-us'] = "Enter the onsite language set 4.";
$text['description-osahf']['en-us'] = "Enter the onsite after hours fee.";
$text['description-osrf']['en-us'] = "Enter the onsite rush fee.";
$text['description-osrt']['en-us'] = "Enter the onsite rush time.";
$text['description-oscf']['en-us'] = "Enter the onsite cancellation fee.";
$text['description-osct']['en-us'] = "Enter the onsite cancellation time.";
$text['description-onsite_instructions']['en-us'] = "Enter the onsite instructions.";
$text['description-charge_callout']['en-us'] = "Enter the charge for callout.";
$text['description-rate_callout']['en-us'] = "Enter the rate for callout.";
$text['description-special_invoice']['en-us'] = "Enter the special invoice.";
$text['description-vrisl1']['en-us'] = "Enter the video remote interpreting language set 1.";
$text['description-vrisl2']['en-us'] = "Enter the video remote interpreting language set 2.";
$text['description-vrisl3']['en-us'] = "Enter the video remote interpreting language set 3.";
$text['description-vrisl4']['en-us'] = "Enter the video remote interpreting language set 4.";
$text['description-vricf']['en-us'] = "Enter the video remote interpreting cancellation fee.";
$text['description-vrict']['en-us'] = "Enter the video remote interpreting cancellation time.";
$text['description-vriahf']['en-us'] = "Enter the video remote interpreting after hours fee.";
$text['description-tls1']['en-us'] = "Enter the translation rate language set 1.";
$text['description-tls2']['en-us'] = "Enter the translation rate language set 2.";
$text['description-tls3']['en-us'] = "Enter the translation rate language set 3.";
$text['description-tls4']['en-us'] = "Enter the translation rate language set 4.";
$text['description-tff']['en-us'] = "Enter the translation formatting fee.";
$text['description-trf']['en-us'] = "Enter the translation rush fee.";

$text['description-clients']['en-us'] = "Client information.";
$text['description-clients']['en-gb'] = "Client information.";
$text['description-clients']['ar-eg'] = "";
$text['description-clients']['de-at'] = ""; //copied from de-de
$text['description-clients']['de-ch'] = ""; //copied from de-de
$text['description-clients']['de-de'] = "";
$text['description-clients']['es-cl'] = "";
$text['description-clients']['es-mx'] = ""; //copied from es-cl
$text['description-clients']['fr-ca'] = ""; //copied from fr-fr
$text['description-clients']['fr-fr'] = "";
$text['description-clients']['he-il'] = "";
$text['description-clients']['it-it'] = "";
$text['description-clients']['nl-nl'] = "";
$text['description-clients']['pl-pl'] = "";
$text['description-clients']['pt-br'] = "";
$text['description-clients']['pt-pt'] = "";
$text['description-clients']['ro-ro'] = "";
$text['description-clients']['ru-ru'] = "";
$text['description-clients']['sv-se'] = "";
$text['description-clients']['uk-ua'] = "";

$text['description-client-edit']['en-us'] = "Client information.";
$text['description-client-edit']['en-gb'] = "Client information.";
$text['description-client-edit']['ar-eg'] = "";
$text['description-client-edit']['de-at'] = ""; //copied from de-de
$text['description-client-edit']['de-ch'] = ""; //copied from de-de
$text['description-client-edit']['de-de'] = "";
$text['description-client-edit']['es-cl'] = "";
$text['description-client-edit']['es-mx'] = ""; //copied from es-cl
$text['description-client-edit']['fr-ca'] = ""; //copied from fr-fr
$text['description-client-edit']['fr-fr'] = "";
$text['description-client-edit']['he-il'] = "";
$text['description-client-edit']['it-it'] = "";
$text['description-client-edit']['nl-nl'] = "";
$text['description-client-edit']['pl-pl'] = "";
$text['description-client-edit']['pt-br'] = "";
$text['description-client-edit']['pt-pt'] = "";
$text['description-client-edit']['ro-ro'] = "";
$text['description-client-edit']['ru-ru'] = "";
$text['description-client-edit']['sv-se'] = "";
$text['description-client-edit']['uk-ua'] = "";

$text['description-client-add']['en-us'] = "Client information.";
$text['description-client-add']['en-gb'] = "Client information.";
$text['description-client-add']['ar-eg'] = "";
$text['description-client-add']['de-at'] = ""; //copied from de-de
$text['description-client-add']['de-ch'] = ""; //copied from de-de
$text['description-client-add']['de-de'] = "";
$text['description-client-add']['es-cl'] = "";
$text['description-client-add']['es-mx'] = ""; //copied from es-cl
$text['description-client-add']['fr-ca'] = ""; //copied from fr-fr
$text['description-client-add']['fr-fr'] = "";
$text['description-client-add']['he-il'] = "";
$text['description-client-add']['it-it'] = "";
$text['description-client-add']['nl-nl'] = "";
$text['description-client-add']['pl-pl'] = "";
$text['description-client-add']['pt-br'] = "";
$text['description-client-add']['pt-pt'] = "";
$text['description-client-add']['ro-ro'] = "";
$text['description-client-add']['ru-ru'] = "";
$text['description-client-add']['sv-se'] = "";
$text['description-client-add']['uk-ua'] = "";

$text['description-clients_import']['en-us'] = "Client Import";
$text['description-clients_import']['en-gb'] = "Client Import";
$text['description-clients_import']['ar-eg'] = "";
$text['description-clients_import']['de-at'] = "Importieren"; //copied from de-de
$text['description-clients_import']['de-ch'] = "Importieren"; //copied from de-de
$text['description-clients_import']['de-de'] = "Importieren";
$text['description-clients_import']['el-gr'] = "Εισαγωγή";
$text['description-clients_import']['es-cl'] = "Importar";
$text['description-clients_import']['es-mx'] = "Importar"; //copied from es-cl
$text['description-clients_import']['fr-ca'] = "Importer"; //copied from fr-fr
$text['description-clients_import']['fr-fr'] = "Importer";
$text['description-clients_import']['he-il'] = "";
$text['description-clients_import']['it-it'] = "";
$text['description-clients_import']['nl-nl'] = "";
$text['description-clients_import']['pl-pl'] = "Importuj";
$text['description-clients_import']['pt-br'] = "Importar";
$text['description-clients_import']['pt-pt'] = "Importat";
$text['description-clients_import']['ro-ro'] = "";
$text['description-clients_import']['ru-ru'] = "Импорт";
$text['description-clients_import']['sv-se'] = "Importera";
$text['description-clients_import']['uk-ua'] = "";
$text['description-clients_import']['tr-tr'] = "İçe Aktar";

$text['button-download_csv']['en-us'] = "Download CSV";
$text['button-download_csv']['en-gb'] = "Download CSV";
$text['button-download_csv']['ar-eg'] = "";
$text['button-download_csv']['de-at'] = "CSV Herunterladen"; //copied from de-de
$text['button-download_csv']['de-ch'] = "CSV Herunterladen"; //copied from de-de
$text['button-download_csv']['de-de'] = "CSV Herunterladen";
$text['button-download_csv']['es-cl'] = "Descarga CSV";
$text['button-download_csv']['es-mx'] = "Descarga CSV"; //copied from es-cl
$text['button-download_csv']['fr-ca'] = "Télécharger CSV"; //copied from fr-fr
$text['button-download_csv']['fr-fr'] = "Télécharger CSV";
$text['button-download_csv']['he-il'] = "";
$text['button-download_csv']['it-it'] = "Scarica CSV";
$text['button-download_csv']['nl-nl'] = "";
$text['button-download_csv']['pl-pl'] = "Pobierz CSV";
$text['button-download_csv']['pt-br'] = "Baixar CSV ";
$text['button-download_csv']['pt-pt'] = "Baixar CSV";
$text['button-download_csv']['ro-ro'] = "";
$text['button-download_csv']['ru-ru'] = "Загрузить в формате CSV";
$text['button-download_csv']['sv-se'] = "Ladda Ned CSV";
$text['button-download_csv']['uk-ua'] = "";

?>
