<?php

	//application details
		$apps[$x]['name'] = "Clients";
		$apps[$x]['uuid'] = "6061d7cc-8beb-494c-b2a6-ea77293aa4c7";
		$apps[$x]['category'] = "App";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Stored client information.";
		$apps[$x]['description']['en-gb'] = "Stored client information.";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "client_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "68cbbfd0-6c3e-45bd-843c-8e48b5b96e75";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "client_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "client_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "client_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "client_import";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "client_upload";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;

	//schema details
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_clients";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "client_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;

		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "access_code";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the client access code.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "active";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the client active status.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "invoice";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the invoice.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "contract_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the contract number.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "client_id";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the client id.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otp_sp_in";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone special instructions.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otp_instructions";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone instructions.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "sp_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the special instruction type.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "invoice_detail";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the invoice information.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "client_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the client name.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "agency";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the agency.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "division";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "county";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the county.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "account_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the account number.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_contact";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division contact.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_address";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division address.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_street";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division street.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_building";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division building.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_suite";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division suite.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_city";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division city.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_state";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division state.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_zip";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division zip.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_phone";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division phone.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_fax";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division fax.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "div_email";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the division email.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bil_contact";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing contact.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bil_address";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing address.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_to_1";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing to 1.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_to_2";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing to 2.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_street";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing street.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_bulding_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing building name.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_suite";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing suite.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_city";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing city.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_state";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing state.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bill_zip";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing zip.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bil_phone";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing phone.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bil_fax";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing fax.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "bil_email";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the billing email.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls1";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 1.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls2";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 2.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls3";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 3.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls4";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 4.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls1a";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 1 after hours.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls2a";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 2 after hours.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls3a";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 3 after hours.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "otpls4a";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the over-the-phone language set 4 after hours.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osls1";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite language set 1.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osls2";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite language set 2.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osls3";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite language set 3.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osls4";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite language set 4.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osahf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite after hours fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osrf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite rush fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osrt";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite rush time.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "oscf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite cancellation fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "osct";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite cancellation time.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "onsite_instructions";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the onsite instructions.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "charge_callout";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the charge for callout.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "rate_callout";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the rate for callout.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "special_invoice";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the special invoice.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vrisl1";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting language set 1.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vrisl2";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting language set 2.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vrisl3";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting language set 3.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vrisl4";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting language set 4.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vricf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting cancellation fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vrict";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting cancellation time.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "vriahf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the video remote interpreting after hours fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "tls1";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation rate language set 1.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "tls2";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation rate language set 2.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "tls3";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation rate language set 3.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "tls4";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation rate language set 4.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "tff";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation formatting fee.";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "trf";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the translation rush fee.";
		$z++;

		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

?>
