<?php

$text['title-agent_live_call']['en-us'] = "Active Calls";
$text['title-agent_live_call']['en-gb'] = "Active Calls";
$text['title-agent_live_call']['ar-eg'] = "";
$text['title-agent_live_call']['de-at'] = "";
$text['title-agent_live_call']['de-ch'] = "";
$text['title-agent_live_call']['de-de'] = "";
$text['title-agent_live_call']['es-cl'] = "";
$text['title-agent_live_call']['es-mx'] = "";
$text['title-agent_live_call']['fr-ca'] = "";
$text['title-agent_live_call']['fr-fr'] = "";
$text['title-agent_live_call']['he-il'] = "";
$text['title-agent_live_call']['it-it'] = "";
$text['title-agent_live_call']['nl-nl'] = "";
$text['title-agent_live_call']['pl-pl'] = "";
$text['title-agent_live_call']['pt-br'] = "";
$text['title-agent_live_call']['pt-pt'] = "";
$text['title-agent_live_call']['ro-ro'] = "";
$text['title-agent_live_call']['ru-ru'] = "";
$text['title-agent_live_call']['sv-se'] = "";
$text['title-agent_live_call']['uk-ua'] = "";

$text['title-agent_inactive_call']['en-us'] = "Inactive Calls";
$text['title-agent_inactive_call']['en-gb'] = "Inactive Calls";
$text['title-agent_inactive_call']['ar-eg'] = "";
$text['title-agent_inactive_call']['de-at'] = "";
$text['title-agent_inactive_call']['de-ch'] = "";
$text['title-agent_inactive_call']['de-de'] = "";
$text['title-agent_inactive_call']['es-cl'] = "";
$text['title-agent_inactive_call']['es-mx'] = "";
$text['title-agent_inactive_call']['fr-ca'] = "";
$text['title-agent_inactive_call']['fr-fr'] = "";
$text['title-agent_inactive_call']['he-il'] = "";
$text['title-agent_inactive_call']['it-it'] = "";
$text['title-agent_inactive_call']['nl-nl'] = "";
$text['title-agent_inactive_call']['pl-pl'] = "";
$text['title-agent_inactive_call']['pt-br'] = "";
$text['title-agent_inactive_call']['pt-pt'] = "";
$text['title-agent_inactive_call']['ro-ro'] = "";
$text['title-agent_inactive_call']['ru-ru'] = "";
$text['title-agent_inactive_call']['sv-se'] = "";
$text['title-agent_inactive_call']['uk-ua'] = "";

$text['title-call_detail_records']['en-us'] = "Call Records";
$text['label-ext']['en-us'] = "Ext.";
$text['label-domain']['en-us'] = "Domain";
$text['label-caller_id_name']['en-us'] = "Caller Name";
$text['label-caller_id_number']['en-us'] = "Caller Number";
$text['label-caller_destination']['en-us'] = "Caller Destination";
$text['label-destination']['en-us'] = "Destination";
$text['label-access_code']['en-us'] = "Access Code";
$text['label-cost_center_id']['en-us'] = "Cost Center ID";
$text['label-employee_id']['en-us'] = "Employee ID";
$text['label-caller_name']['en-us'] = "Caller Name";
$text['label-interpret_language']['en-us'] = "Language";
$text['label-interpreter_id']['en-us'] = "Interpreter ID";
$text['label-fusion_group_interpreter_id']['en-us'] = "Fusion Group Interpreter ID";
$text['label-date']['en-us'] = "Date";
$text['label-time']['en-us'] = "Time";
$text['label-duration']['en-us'] = "Duration";

$text['label-inbound']['en-us'] = "Inbound";
$text['label-outbound']['en-us'] = "Outbound";
$text['label-local']['en-us'] = "Local";
$text['label-answered']['en-us'] = "Answered";
$text['label-voicemail']['en-us'] = "Voicemail";
$text['label-cancelled']['en-us'] = "Cancelled";
$text['label-failed']['en-us'] = "Failed";

$text['label-refresh_pause']['en-us'] = "Pause Refresh";
$text['label-refresh_pause']['en-gb'] = "Pause Refresh";
$text['label-refresh_pause']['ar-eg'] = "";
$text['label-refresh_pause']['de-at'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-ch'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-de'] = "Seite neu laden deaktivieren";
$text['label-refresh_pause']['es-cl'] = "Actualizar Pausa";
$text['label-refresh_pause']['es-mx'] = "Actualizar Pausa"; //copied from es-cl
$text['label-refresh_pause']['fr-ca'] = "Pause Actualiser"; //copied from fr-fr
$text['label-refresh_pause']['fr-fr'] = "Pause Actualiser";
$text['label-refresh_pause']['he-il'] = "עצור רענון";
$text['label-refresh_pause']['it-it'] = "Interrompi";
$text['label-refresh_pause']['nl-nl'] = "Stop verversen";
$text['label-refresh_pause']['pl-pl'] = "Pauzuj odświeżanie";
$text['label-refresh_pause']['pt-br'] = "Pausar atualizaÃ§Ã£o";
$text['label-refresh_pause']['pt-pt'] = "Pausa Atualizar";
$text['label-refresh_pause']['ro-ro'] = "";
$text['label-refresh_pause']['ru-ru'] = "Приостановить обновление";
$text['label-refresh_pause']['sv-se'] = "Paus Uppdatera";
$text['label-refresh_pause']['uk-ua'] = "ÐŸÑ€Ð¸Ð¿Ð¸Ð½Ð¸Ñ‚Ð¸ Ð¾Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ";

$text['label-refresh_enable']['en-us'] = "Enable Refresh";
$text['label-refresh_enable']['en-gb'] = "Enable Refresh";
$text['label-refresh_enable']['ar-eg'] = "";
$text['label-refresh_enable']['de-at'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-ch'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-de'] = "Seite neu laden aktivieren";
$text['label-refresh_enable']['es-cl'] = "Activar Actualizar";
$text['label-refresh_enable']['es-mx'] = "Activar Actualizar"; //copied from es-cl
$text['label-refresh_enable']['fr-ca'] = "Activer Actualiser"; //copied from fr-fr
$text['label-refresh_enable']['fr-fr'] = "Activer Actualiser";
$text['label-refresh_enable']['he-il'] = "אפשר רענון";
$text['label-refresh_enable']['it-it'] = "Abilita Aggiornamento";
$text['label-refresh_enable']['nl-nl'] = "Start verversen";
$text['label-refresh_enable']['pl-pl'] = "Włącz odświeżanie";
$text['label-refresh_enable']['pt-br'] = "Habilitar atualizaÃ§Ã£o";
$text['label-refresh_enable']['pt-pt'] = "Habilitar Atualização";
$text['label-refresh_enable']['ro-ro'] = "";
$text['label-refresh_enable']['ru-ru'] = "Включить обновление";
$text['label-refresh_enable']['sv-se'] = "Aktivera Uppdatering";
$text['label-refresh_enable']['uk-ua'] = "Ð’ÐºÐ»ÑŽÑ‡Ð¸Ñ‚Ð¸ Ð¾Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ";

$text['label-call_direction']['en-us'] = "Call Direction";
$text['label-call_direction']['en-gb'] = "Call Direction";
$text['label-call_direction']['ar-eg'] = "";
$text['label-call_direction']['de-at'] = "Anruf Richtung"; //copied from de-de
$text['label-call_direction']['de-ch'] = "Anruf Richtung"; //copied from de-de
$text['label-call_direction']['de-de'] = "Anruf Richtung";
$text['label-call_direction']['es-cl'] = "Dirección de la llamada";
$text['label-call_direction']['es-mx'] = "Dirección de la llamada"; //copied from es-cl
$text['label-call_direction']['fr-ca'] = "Sens de l'appel"; //copied from fr-fr
$text['label-call_direction']['fr-fr'] = "Sens de l'appel";
$text['label-call_direction']['he-il'] = "כיוון שיחה";
$text['label-call_direction']['it-it'] = "Direzione Chiamata";
$text['label-call_direction']['nl-nl'] = "Oproep richting";
$text['label-call_direction']['pl-pl'] = "Kierunek rozmowy";
$text['label-call_direction']['pt-br'] = "DireÃ§Ã£o da chamada";
$text['label-call_direction']['pt-pt'] = "Direção da chamada";
$text['label-call_direction']['ro-ro'] = "";
$text['label-call_direction']['ru-ru'] = "Направление вызова";
$text['label-call_direction']['sv-se'] = "Samtals Riktning";
$text['label-call_direction']['uk-ua'] = "напрямок виклику";

$text['label-start_timestamp']['en-us'] = "Operator start interaction with client";
$text['label-start_timestamp']['en-gb'] = "Operator start interaction with client";
$text['label-start_timestamp']['ar-eg'] = "";
$text['label-start_timestamp']['de-at'] = ""; //copied from de-de
$text['label-start_timestamp']['de-ch'] = ""; //copied from de-de
$text['label-start_timestamp']['de-de'] = "";
$text['label-start_timestamp']['es-cl'] = "";
$text['label-start_timestamp']['es-mx'] = ""; //copied from es-cl
$text['label-start_timestamp']['fr-ca'] = ""; //copied from fr-fr
$text['label-start_timestamp']['fr-fr'] = "";
$text['label-start_timestamp']['he-il'] = "";
$text['label-start_timestamp']['it-it'] = "";
$text['label-start_timestamp']['nl-nl'] = "";
$text['label-start_timestamp']['pl-pl'] = "";
$text['label-start_timestamp']['pt-br'] = "";
$text['label-start_timestamp']['pt-pt'] = "";
$text['label-start_timestamp']['ro-ro'] = "";
$text['label-start_timestamp']['ru-ru'] = "";
$text['label-start_timestamp']['sv-se'] = "";
$text['label-start_timestamp']['uk-ua'] = "";

$text['title_description-agent_live_call']['en-us'] = "Monitor the active call of the extension and store details of the caller.";
$text['title_description-agent_live_call']['en-gb'] = "Monitor the active call of the extension and store details of the caller.";
$text['title_description-agent_live_call']['ar-eg'] = "";
$text['title_description-agent_live_call']['de-at'] = "";
$text['title_description-agent_live_call']['de-ch'] = "";
$text['title_description-agent_live_call']['de-de'] = "";
$text['title_description-agent_live_call']['es-cl'] = "";
$text['title_description-agent_live_call']['es-mx'] = "";
$text['title_description-agent_live_call']['fr-ca'] = "";
$text['title_description-agent_live_call']['fr-fr'] = "";
$text['title_description-agent_live_call']['he-il'] = "";
$text['title_description-agent_live_call']['it-it'] = "";
$text['title_description-agent_live_call']['nl-nl'] = "";
$text['title_description-agent_live_call']['pl-pl'] = "";
$text['title_description-agent_live_call']['pt-br'] = "";
$text['title_description-agent_live_call']['pt-pt'] = "";
$text['title_description-agent_live_call']['ro-ro'] = "";
$text['title_description-agent_live_call']['ru-ru'] = "";
$text['title_description-agent_live_call']['sv-se'] = "";
$text['title_description-agent_live_call']['uk-ua'] = "";

$text['message-missing_required']['en-us'] = "Missing required information.";
$text['message-missing_required']['en-gb'] = "Missing required information.";

?>
